combiner:
  fc_size: "{{[64,128]}}"
  num_fc_layers: "{{[1,2]}}"
  type: concat
input_features:
- name: age
  tied_weights: null
  type: numerical
  norm: layer_norm
- name: sex
  tied_weights: null
  type: category
  vocab:
  - <UNK>
  - male
  - female
- name: chest-pain-type
  tied_weights: null
  type: category
  vocab:
  - <UNK>
  - asymptomatic
  - non-anginal pain
  - atypical angina
  - typical angina
- name: resting-blood-pressure
  tied_weights: null
  type: numerical
- name: cholesterol
  tied_weights: null
  type: numerical
- name: fasting-blood-sugar
  tied_weights: null
  type: category
  vocab:
  - <UNK>
  - 'False'
  - 'True'
- name: resting-ecg
  tied_weights: null
  type: category
  vocab:
  - <UNK>
  - normal
  - left ventricular hypertrophy
  - ST-T wave abnormality
- name: max-heart-rate
  tied_weights: null
  type: numerical
- name: exercise-angina
  tied_weights: null
  norm: layer_norm
  type: category
  vocab:
  - <UNK>
  - 'no'
  - 'yes'
- name: oldpeak
  tied_weights: null
  type: numerical
  norm: layer_norm
- name: slope
  tied_weights: null
  type: category
  vocab:
  - <UNK>
  - unsloping
  - flat
  - downsloping
- name: colored-vessels
  tied_weights: null
  type: category
  vocab:
  - <UNK>
  - '0'
  - '1'
  - '2'
  - '3'
  - '?'
- name: thal
  tied_weights: null
  type: category
  vocab:
  - <UNK>
  - normal
  - reversable defect
  - fixed defect
  - '?'
output_features:
- dependencies: []
  loss:
    confidence_penalty: 0
    robust_lambda: 0
    threshold: 0.5
    weight: 1
  name: narrowing-diagnosis
  reduce_dependencies: sum
  reduce_input: sum
  threshold: 0.5
  type: binary
  weight: 1
preprocessing:
  bag:
    fill_value: ''
    format: space
    lowercase: false
    missing_value_strategy: fill_with_const
    most_common: 10000
  binary:
    fill_value: 0
    missing_value_strategy: fill_with_const
  category:
    fill_value: <UNK>
    lowercase: false
    missing_value_strategy: fill_with_const
    most_common: 10000
  force_split: false
  image:
    in_memory: true
    missing_value_strategy: backfill
    resize_method: crop_or_pad
  numerical:
    fill_value: 0
    missing_value_strategy: fill_with_const
  sequence:
    fill_value: ''
    format: space
    lowercase: false
    missing_value_strategy: fill_with_const
    most_common: 20000
    padding: right
    padding_symbol: <PAD>
    sequence_length_limit: 256
    unknown_symbol: <UNK>
  set:
    fill_value: ''
    format: space
    lowercase: false
    missing_value_strategy: fill_with_const
    most_common: 10000
  split_probabilities: !!python/tuple
  - 0.7
  - 0.1
  - 0.2
  stratify: null
  text:
    char_format: characters
    char_most_common: 70
    char_sequence_length_limit: 1024
    fill_value: ''
    lowercase: true
    missing_value_strategy: fill_with_const
    padding: right
    padding_symbol: <PAD>
    unknown_symbol: <UNK>
    word_format: space_punct
    word_most_common: 20000
    word_sequence_length_limit: 256
  timeseries:
    fill_value: ''
    format: space
    missing_value_strategy: fill_with_const
    padding: right
    padding_value: 0
    timeseries_length_limit: 256
random_seed: 42
training:
  batch_size: 16
  bucketing_field: null
  decay: false
  decay_rate: 0.96
  decay_steps: 10000
  dropout_rate: 0.0
  early_stop: 5
  epochs: 100
  eval_batch_size: 0
  gradient_clipping: null
  increase_batch_size_on_plateau: 0
  increase_batch_size_on_plateau_max: 512
  increase_batch_size_on_plateau_patience: 5
  increase_batch_size_on_plateau_rate: 2
  learning_rate: "{{[0.001, 0.005, 0.0005]}}"
  learning_rate_warmup_epochs: 5
  optimizer:
    beta1: 0.9
    beta2: 0.999
    epsilon: 1.0e-08
    type: adam
  reduce_learning_rate_on_plateau: 0
  reduce_learning_rate_on_plateau_patience: 5
  reduce_learning_rate_on_plateau_rate: 0.5
  regularization_lambda: 0
  regularizer: l2
  staircase: false
  validation_field: combined
  validation_measure: loss
